Repository jenkinsci/jsch-plugin, pull requests merged in 2020-01, with the labels that each got.

#12 Configure release drafter.
  .github/release-drafter.yml
Labels: chore

#10 [WEBSITE-637] Use GitHub as the source of documentation
  CHANGELOG.md
  README.md
  pom.xml
Labels: documentation, ready-to-merge

#11 Add trilead-api and bump jenkins core
  Jenkinsfile
  pom.xml
Labels: dependencies, ready-to-merge
